Repository kaizengrowth/CityCamp_AI, pull requests merged in 2025-08, with the labels that each got.

#41 feat(pdf-viewer): improve Safari popup handling with advanced fallback methods
  frontend/src/components/PDFViewer.tsx
  frontend/src/utils/pdfUtils.ts
Labels: bug, enhancement, ui

#50 new CI/CD pipeline & db migrations for simplified EC2 deployment
  .github/workflows/deploy.yml
  .gitignore
  README.md
  aws/terraform/.terraform.lock.hcl
  backend/alembic/versions/000_create_users_table.py
  backend/alembic/versions/001_add_rag_document_models.py
  backend/app/core/config.py
  backend/app/core/database.py
  backend/app/services/ai_categorization_service.py
  backend/app/services/document_processing_service.py
  backend/app/services/research_service.py
  backend/requirements.txt
  deployment_trigger.txt
  docs/ARCHITECTURE_IMPROVEMENTS.md
  docs/CHATBOT_EVALUATION_README.md
  docs/ENHANCED_CHATBOT_GUIDE.md
  docs/QUICKSTART.md
  docs/README.md
  docs/SCRAPER_TEST_README.md
  docs/TROUBLESHOOTING.md
  docs/TULSA_ARCHIVE_SCRAPER_README.md
  frontend/nginx.conf
  manual_ec2_deploy.sh
  quick_ec2_deploy.sh
  scripts/activate-dev.sh
  scripts/check_production_meetings.py
  scripts/process_minutes_folder.py
  scripts/reprocess_all_production_meetings.py
  scripts/run_comprehensive_tulsa_scraper.py
  scripts/seed_sample_campaigns.py
  scripts/seed_tulsa_organizations.py
  scripts/start-dev.sh
Labels: bug, dependencies, devops

#51 Removed default district/reps
  backend/app/api/v1/endpoints/representatives.py
  backend/app/services/geocoding_service.py
  frontend/src/components/DistrictMapper.tsx
  frontend/src/pages/ContactRepresentativesPage.tsx
Labels: bug, External API's, ui
